notifications:
  email: false
sudo: true
language: python
cache:
- pip
python:
- '2.7'
- '3.5'
before_install:
- travis_retry pip install --upgrade pip setuptools py
- travis_retry pip install twine wheel coveralls
install:
- travis_retry pip install -e .[all]
script:
- "./run-tests.sh"
after_success:
- coveralls
deploy:
  provider: pypi
  user: anthropoid
  password:
    secure: t7ub9BylTbHWQaudxO4mZdl4iU0SK1/e/FDZghU0H4ELyAoPYtQTHFPKWY6AyzcFMqzTnAxZVqhcnBa7cEvnLxB9srKbeRWYW1r1ChJf7KF3HOVjZydV9rPTBiHXfTHgJUvXRy0qP+cRh4mn1ATpmC4B78r2H4k2fnxUGHZMSpELU01T64n/3zm5Fpp+9R/pq6MtQwlOV852AXjN2v+Ub3ygEApba/c2bpPJTshZq3DH4KwBUtO93PUfrOZ2wFcRsKoDmVt3u/fWfBXZjMBjXVqebJsAv5Gk9qrN+zfhiIte5kyAn4tNNTdkPloG/quE6LhvnmgA/1oEo1Yf71ot12SFo558KB6W9Xo9jGieQRBQorcG+m69CjDIa1VSbAUirzacO5lCjyoVhom2Dos0cb7IpwzoE0DFN8eEizpy1fIIKVBqDj/kBhdxavLv9KsnEHCIXPpEcc4C8UjAvsXic3S3FCca3coj3orInhvIa5oxZi6bXSUdtqbIBspR8sWvxrNKBE80ntI/dIsZ2oHWbvKPDZodjYUiI/vMYo+IoVvzXZJ11CJt5PY83tjo3ra0CFDDGhbemsFOoL9rPpT5unHBJuR2+3txDGSRYy681MzRhZ/F1HqB3dg7SM/Y3BPNO+eyBG7cDEE3FxDIPcQJ1rtH/pHt4uwwlmtfp1VYUbM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '2.7'
    branch: master
